# Generated by Django 5.1.1 on 2024-12-03 06:38

import config.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64, verbose_name='Category')),
                ('user_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='User name')),
                ('user_tag', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tag name')),
                ('user_location', models.CharField(blank=True, max_length=32, null=True, verbose_name='Location')),
                ('description', models.TextField(verbose_name='Description')),
                ('screenshot', models.ImageField(blank=True, null=True, storage=config.utilities.UUIDFileStorage(), upload_to='screenshot_application/%d-%m-%Y')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of updating')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
                ('operator', models.ManyToManyField(blank=True, to='personal.operator')),
                ('workstation', models.ManyToManyField(blank=True, to='personal.workstation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
