# Generated by Django 5.1.1 on 2024-10-29 13:45

import config.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_nonstop', models.BooleanField(default=True)),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of updating')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('media', models.FileField(storage=config.utilities.UUIDFileStorage(), upload_to='publish/%d-%m-%Y')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of updating')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
                ('locations', models.ManyToManyField(blank=True, to='publish.location')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
