# Generated by Django 5.1.1 on 2024-12-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('p', 'Processing'), ('c', 'Complete')], default='w', max_length=1, verbose_name='Status')),
                ('action', models.CharField(blank=True, max_length=64, null=True, verbose_name='Action')),
                ('command', models.TextField(blank=True, null=True, verbose_name='Command')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of updating')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
