# Generated by Django 5.1.1 on 2024-12-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('info', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(max_length=64, unique=True, verbose_name='Username')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('tag', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Tag')),
                ('birthday', models.DateField(blank=True, max_length=32, null=True, verbose_name='Birthday')),
                ('is_head', models.BooleanField(default=False, verbose_name='Head')),
                ('is_admin', models.BooleanField(default=False, verbose_name='System administrator')),
                ('date_ecp', models.DateField(blank=True, max_length=32, null=True, verbose_name='Date end ECP')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of updating')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_printer', models.CharField(max_length=32, unique=True, verbose_name='IP-address printer')),
                ('model_printer', models.CharField(max_length=32, verbose_name='Model printer')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of updating')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
                ('history', models.ManyToManyField(blank=True, to='personal.history')),
            ],
            options={
                'ordering': ['ip_printer'],
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_desktop', models.SlugField(max_length=32, unique=True, verbose_name='Name desktop')),
                ('ip_desktop', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='IP-address desktop')),
                ('mac_desktop', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='MAC-address desktop')),
                ('ip_assistant', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='IP-address assistant')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of updating')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
                ('printers', models.ManyToManyField(blank=True, to='personal.printer')),
            ],
            options={
                'ordering': ['name_desktop'],
            },
        ),
    ]
